#version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: pantry_db
    ports:
      #map the laptop's port to the container's port
      - "5433:5432" 
    volumes:
      #saves the db data in a volume locally on the computer
      #allows data to persist even after contianter is stopped or restarted
      - postgres_data:/var/lib/postgresql/data 
    environment:
      #these vairables configure the postgres container
      #will be read from the .env file
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  #this officially creates the volume
  postgres_data:
